#cloud-config
repo_update: true
repo_upgrade: all

write_files:
 - path: /etc/supervisord.conf
   content: |
           [unix_http_server]
           file=/tmp/supervisor.sock

           [supervisord]
           logfile=/tmp/supervisord.log
           logfile_maxbytes=50MB
           logfile_backups=10
           loglevel=info
           pidfile=/tmp/supervisord.pid
           nodaemon=false
           silent=false
           minfds=1024
           minprocs=200

           [rpcinterface:supervisor]
           supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

           [supervisorctl]
           serverurl=unix:///tmp/supervisor.sock

           [program:pypi_server]
           command=sudo python3 -m pypiserver -v -p '${pypi_port}' -P /opt/pypi_server/htpasswd -a download,update,list /opt/pypi_server/packages
           directory=/opt/pypi_server
           autorestart=true

runcmd:
  - yum update -y
  - yum install -y python3 httpd-tools
  - mkfs -t xfs '${mount_point}' >& /dev/null
  - mkdir /opt/pypi_server/
  - chmod u+x /opt/run_pypi_server.sh
  - mount '${mount_point}' /opt/pypi_server/
  - mkdir /opt/pypi_server/packages
  - htpasswd -b -c /opt/pypi_server/htpasswd '${pypi_username}' '${pypi_password}'
  - python3 -m pip install supervisor passlib pypiserver
  - $(which supervisord)
  - sleep 1
  - $(which supervisorctl) status
