#cloud-config
repo_update: true
repo_upgrade: all

write_files:
  - path: /opt/run_pypi_server.sh
    content: |
        #!/usr/bin/env bash

        sudo yum update -y
        sudo yum install -y python3
        sudo python3 -m pip install passlib
        sudo python3 -m pip install pypiserver

        sudo python3 -m pypiserver -v -p 8080 -P /opt/pypi_server/htpasswd -a download,update,list /opt/pypi_server/packages
  - path: /etc/systemd/system/pypi_server.service
    content: |
        [Unit]
        Description=Private Pypi server
        After=network.target

        [Service]
        Type=simple
        ExecStart=/opt/run_pypi_server.sh
        KillMode=process
        Restart=on-failure
        RestartSec=42s

        [Install]
        WantedBy=default.target
runcmd:
  - yum update -y
  - yum install -y httpd-tools
  - mkfs -t xfs '${mount_point}' >& /dev/null
  - mkdir /opt/pypi_server/
  - chmod u+x /opt/run_pypi_server.sh
  - mount '${mount_point}' /opt/pypi_server/
  - mkdir /opt/pypi_server/packages
  - htpasswd -b -c /opt/pypi_server/htpasswd '${pypi_username}' '${pypi_password}'
  - systemctl enable pypi_server.service
  - systemctl start pypi_server.service
  - sleep 1